### ISSUE TITLE
Example throws TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by einkoro** [ssttevee/js-cfw-formdata-polyfill#3]
Attempting to run the [polyfill example](https://github.com/ssttevee/js-cfw-formdata-polyfill/blob/master/example/polyfill/src/main.js) as-is with wrangler dev throws `TypeError: Right-hand side of 'instanceof' is not callable` upon calling `fd.entries()` in the loop.

The stack trace isn't the nicest without the eval sourcemaps in workers unfortunately:
```
TypeError: Right-hand side of 'instanceof' is not callable
    at l (worker.js:1:2252)
    at worker.js:1:3502
    at Array.map (<anonymous>)
    at f.[Symbol.iterator] (worker.js:1:3482)
    at f.next (<anonymous>)
    at f.entries (worker.js:1:3548)
    at entries.next (<anonymous>)
    at worker.js:1:10734
```

Just to double check before I poke at this more would this be the correct ProvidePlugin() config for webpack?

```
new webpack.ProvidePlugin({
    Blob: '@ssttevee/blob-ponyfill/blob',
    File: '@ssttevee/blob-ponyfill/file',
    FileReaderSync: '@ssttevee/blob-ponyfill/filereadersync'
})
```

**Comment by ssttevee** [comment]
The `ProvidePlugin` usage seems correct to me, but stack trace seems to suggest that `Blob` is not defined.

Have you tried building without uglifying? It may make some issues more apparent.

Otherwise, I may need to inspect the resulting bundle to see what's going wrong.

**Comment by einkoro** [comment]
Without minification its a little easier to navigate:
```
TypeError: Right-hand side of 'instanceof' is not callable
    at normalizeEntry (worker.js:214:18)
    at worker.js:300:65
    at Array.map (<anonymous>)
    at lib.[Symbol.iterator] (worker.js:300:32)
    at lib.next (<anonymous>)
    at lib.entries (worker.js:303:37)
    at entries.next (<anonymous>)
    at handleRequest (worker.js:995:36)
```
So the type error occurs @ https://github.com/ssttevee/js-formdata-ponyfill/blob/master/src/index.ts#L7

Resulting bundle: https://gist.github.com/einkoro/9dcb70342d99d2658838044e2a1c57a1

One thing that jumped out as strange to me is the redundant instances of Blob/blob. 
```
// EXTERNAL MODULE: ./node_modules/@ssttevee/blob-ponyfill/blob.js
var blob = __webpack_require__(699);
;// CONCATENATED MODULE: ./node_modules/@ssttevee/formdata-ponyfill/lib/index.js
/* provided dependency */ var Blob = __webpack_require__(699);
```

**Comment by ssttevee** [comment]
The resulting bundle suggests that there's a problem with the `webpack.ProvidePlugin` config.

Try changing it to this:

```
new webpack.ProvidePlugin({
    Blob: ['@ssttevee/blob-ponyfill/blob', 'default'],
    File: ['@ssttevee/blob-ponyfill/file', 'default'],
    FileReaderSync: ['@ssttevee/blob-ponyfill/filereadersync', 'default'],
})
```

`webpack.ProvidePlugin` works similar to NodeJS's `require` function. That means all of a module's exports are provided as an object. However, the example assumes an esm environment, so it's necessary to explicitly provide the `'default'` property.

**Comment by einkoro** [comment]
That was indeed the problem. Thanks for taking a look at it.
